version: '3.9'
services:
  db-test:
    container_name: db-test
    image: mysql:8.0.27
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${IP_TEST}:${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "${MYSQL_DATABASE}_test"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - summit-database:/var/lib/mysql

  php-test:
    container_name: php-fpm-test
    build:
      dockerfile: ./dev/docker/php-fpm/Dockerfile
      context: .
    ports:
      - "${IP_TEST}:${PHP_PORT}:9001"
    volumes:
      - ./:/var/www/symfony:cached
    depends_on:
      - db-test

volumes:
  summit-database:
