version: '3.9'
services:
  db:
    container_name: db
    image: mysql:8.0.27
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${IP}:${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - summit-database:/var/lib/mysql

  php:
    container_name: php-fpm
    build:
      dockerfile: ./dev/docker/php-fpm/Dockerfile
      context: .
    ports:
      - "${IP}:${PHP_PORT}:9001"
    volumes:
      - ./:/var/www/symfony:cached
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.21.5
    ports:
      - "${IP}:${NGINX_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony:cached
      - ./dev/docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf

volumes:
  summit-database:
